name: OtoBus
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_spinkit: "^4.1.2"
  modal_progress_hud: ^0.1.3
  http: ^0.12.2
  image_picker: ^0.6.7+22
  firebase_core: ^0.5.0+1
  firebase_auth: ^0.18.1+2
  firebase_database: ^4.1.1
  cloud_firestore: ^0.14.3
  firebase_helpers: ^0.2.2

  flutter_session: ^0.1.1
  fluttertoast: ^6.0.0
  curved_navigation_bar: ^0.3.7
  google_maps_flutter: ^1.0.3
  geolocator: ^6.1.1
  cupertino_icons: ^1.0.0
  geocoding: ^1.0.5
  geocoder: ^0.2.1
  provider: ^4.1.2
  flutter_map: ^0.9.0
  flutter_polyline_points: ^0.2.0
  connectivity: ^0.4.9+5
  custom_switch: ^0.0.1
  flutter_geofire:  ^1.0.2
  firebase_messaging: ^7.0.3
  intl: ^0.16.1
  maps_toolkit: ^1.1.0+1
  audioplayers: ^0.16.2
  get_storage: ^1.3.0
  smooth_star_rating: ^1.1.1
  url_launcher: ^5.7.10
  percent_indicator: "^2.1.7+2"
  gradient_bottom_navigation_bar: ^1.0.0+4
  flutter_local_notifications: 1.4.4+4
  cube_transition: ^1.0.2
  page_transition: ^1.1.7+6
  flutter_ringtone_player: 
  overlay_support: 
  random_string: 
  table_calendar: ^2.2.1
  shared_preferences: ^0.5.4+5
  googleapis: ^0.55.0
  googleapis_auth: ^0.2.12
  flutter_datetime_picker: 
  flutter_cupertino_date_picker: 

  flutter_mapbox_autocomplete: 
    git:
      url: https://github.com/maysoonabed/flutter_mapbox_autocomplete.git


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_launcher_icons: "^0.8.0"

flutter_icons:
   android: true
   #ios: true
   image_path: "dev_asses/l2.png"  

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  uses-material-design: true
  assets:
    - phpfiles/cardlic/
    - lib/Images/
    - request_notifi.mp3

  fonts:
    - family: Pacifico
      fonts:
        - asset: lib/Font/Pacifico-Regular.ttf
    - family: ArefRuqaaR
      fonts:
        - asset: lib/Font/ArefRuqaa-Regular.ttf
    - family: ArefRuqaaB
      fonts:  
        - asset: lib/Font/ArefRuqaa-Bold.ttf
    - family: Lemonada
      fonts:  
        - asset: lib/Font/Lemonada-VariableFont_wght.ttf              
  